<!DOCTYPE html><html><head><link rel="stylesheet" type="text/css" href="/css/pack/9fa3f098ed2d8da5a416d4ad635a6520.css"></head><body><script type="text/javascript" src="/js/pack/f95d883bd1db464283f2e437cee95b50.js"></script><script type="module">var manager,func;window.addEventListener("error",function(r){if(r.error&&r.error.name==="lderror"&&r.error.error&&r.error!==r.error.error){console.warn("uncaught lderror",r.error);console.warn("with its internal Error object thrown:");r.preventDefault();return setTimeout(function(){throw r.error.error},0)}});window.addEventListener("unhandledrejection",function(r){if(r.reason&&r.reason.name==="lderror"&&r.reason.error){console.warn("Unhandled rejection with lderror:",r.reason);console.warn("with its internal Error object thrown:");throw r.reason.error;return r.preventDefault()}});manager=new block.manager({registry:function(r){var e,n,o,t,a;e=r.ns,n=r.name,o=r.version,t=r.path,a=r.type;if(a==="block"){return"/error/block.html"}return"/js/error/dep.js"}});manager.from({name:"error"},{root:document.body}).then(function(r){});setTimeout(function(){throw lderror(1314)},0);func=new Function("console.log('try to throw an Error in `new Function`');throw new Error()");func();</script></body></html>